### ISSUE TITLE
version 6.2.4 import error on Windows

### ISSUE THREAD

**Issue by psi-jmonaco** [ingeniamc/ingenialink-python#169]
My setup is python 3.9 via Anaconda (2021.11) with a dedicated clean environment as a starting point for working with IngeniaLink.

ingenialink and ingeniamotion are installed via pip under Anaconda control, and the following versions of ingenia-related packages are present ...

```
(ingenia) C:\Users\###>conda list ingenia*
# packages in environment at C:\Users\JeffMonaco\anaconda3\envs\ingenia:
#
# Name                    Version                   Build  Channel
ingenialink               6.2.4                    pypi_0    pypi
ingenialogger             0.2.1                    pypi_0    pypi
ingeniamotion             0.5.4                    pypi_0    pypi
```

Attempts to perform a basic import of ingenialink show the following error stack trace ...

```
import ingenialink as il
Traceback (most recent call last):

  File "C:\Users\###\AppData\Local\Temp/ipykernel_2504/3695347531.py", line 1, in <module>
    import ingenialink as il

  File "C:\Users\###\anaconda3\envs\ingenia\lib\site-packages\ingenialink\__init__.py", line 1, in <module>
    from .network import NetworkMonitor, NET_PROT, \

  File "C:\Users\###\anaconda3\envs\ingenia\lib\site-packages\ingenialink\network.py", line 4, in <module>
    from ._ingenialink import lib, ffi

ImportError: DLL load failed while importing _ingenialink: The specified module could not be found.

```

**Comment by GullinBustin** [comment]
Seem WinPcap is not installed. Please install it and try it again. I leave you the link [here](https://www.winpcap.org/install/).

**Comment by psi-jmonaco** [comment]
Thanks for the prompt reply. The PCAP program was the issue.
