### ISSUE TITLE
serial connection to Pluto drive - MotionLab vs IngeniaLink python binding

### ISSUE THREAD

**Issue by psi-jmonaco** [ingeniamc/ingenialink-python#170]
**SETUP** Pluto drive with actuator powered with an external power supply @ 15 V. Pluto firmware version 2.7.8

**What works**
Can use MotionLab2 software to configure drive, use move interface to perform homing, position control, etc. 

**What does not work**
From a restart of Windows system, without running MotionLab2, attempt to use IngeniaLink python bindings to connect to the drive over serial connection via USB.

Per the following command history, the device is found on COM3 using the network.scan_slaves() method, and this matches the port info shown for COM ports in the OS.

Per the following, the connection to the drive over serial COM3 fails on the first attempt. Subsequent attempts to connect are also unsuccessful because the port is now in use.

```
import ingenialink as il
Cannot load IXXAT vcinpl library: Could not find module 'vcinpl' (or one of its dependencies). Try using the full path with constructor syntax.

from ingenialink.serial.network import SerialNetwork

network = SerialNetwork()

f = network.scan_slaves()

f
Out[5]: ['COM3']

target = f[0]

target
Out[7]: 'COM3'

servo = network.connect_to_slave(target,
                                     "../../resources/dictionaries/"
                                     "eve-core_1.8.1.xdf")
Traceback (most recent call last):

  File "C:\Users\###\AppData\Local\Temp/ipykernel_6024/2623984246.py", line 1, in <module>
    servo = network.connect_to_slave(target,

  File "C:\Users\###\anaconda3\envs\ingenia\lib\site-packages\ingenialink\serial\network.py", line 86, in connect_to_slave
    raise ILError('Could not connect to "{}"'.format(target))

ILError: Could not connect to "COM3"


servo = network.connect_to_slave(target,
                                     "../../resources/dictionaries/"
                                     "eve-core_1.8.1.xdf")
Traceback (most recent call last):

  File "C:\Users\###\AppData\Local\Temp/ipykernel_6024/2623984246.py", line 1, in <module>
    servo = network.connect_to_slave(target,

  File "C:\Users\###\anaconda3\envs\ingenia\lib\site-packages\ingenialink\serial\network.py", line 72, in connect_to_slave
    raise_null(self.__net_interface)

  File "C:\Users\###\anaconda3\envs\ingenia\lib\site-packages\ingenialink\utils\_utils.py", line 251, in raise_null
    raise exc.ILCreationError(msg)

ILCreationError: Serial port open failed (Device is in use)
```

**Comment by mguirg3** [comment]
I am having the same issue. Have you been able to figure out a solution?

**Comment by psi-jmonaco** [comment]
unfortunately no
